import enum

class Pipe(enum.Enum):
    VERTICAL_PIPE = "|"
    HORIZONTAL_PIPE = "-"
    NINETY_DEGREE_PIPE_NORTH_AND_EAST = "L"
    NINETY_DEGREE_PIPE_NORTH_AND_WEST = "J"
    NINETY_DEGREE_PIPE_SOUTH_AND_WEST = "7"
    NINETY_DEGREE_PIPE_SOUTH_AND_EAST = "F"
    GROUND = "."
    STARTING_POSITION = "S"
    EXPANDED_POINT = "X"
